### ISSUE TITLE
[Feat] 번개 개최 Step0: 핑글 개최 안내 페이지 뷰 구현 

### ISSUE THREAD

**Issue by bangMinjI98** [TeamPINGLE/PINGLE-iOS#10]
## ❇️ 어떤 기능인가요?
- Step0: 핑글 개최 안내 페이지 뷰

## ❇️ 뷰 및 기능 설계도

 ![이름 없는 노트북-01](https://github.com/TeamPINGLE/PINGLE-iOS/assets/113960786/a2807ab8-9318-4b2b-91c7-eb87091a5909) 
![image](https://github.com/TeamPINGLE/PINGLE-iOS/assets/113960786/de7ceab6-83f5-4943-9064-96fbe40c331f) 

## ❇️ TODO
- [ ] 나가기 버튼 구현 
- [ ] UILabel (StringLiterals 등록 후 사용) 
- [ ] UIImageView (UIImage는 ImageLiterals 등록 후 사용) 
- [ ] 기기대응 확인하기
