### ISSUE TITLE
[Fix] 온보딩, 설정 플로우 QA 반영

### ISSUE THREAD

**Issue by alstn38** [TeamPINGLE/PINGLE-iOS#107]
## ❇️ 어떤 수정인가요?

- 온보딩, 설정 플로우 QA 반영
- 스플래쉬 분기 처리 과정에서 큰 문제가 발생하여 빠른 수정하겠습니다.

## ❇️ 예상했던 결과는 무엇인가요?

- 앱 중간에 나갈 경우에도 분기처리가 잘 작동할 것입니다.

## ❇️ TODO
- [x] 스플래쉬 로고 영역 중앙 정력
- [ ] 준비가 끝났어요: 제목 텍스트 행간 좁음
- [ ] 설정화면 타이틀 설정
- [ ] 나의 단체 탭 클릭시 공사장 뷰 이동
- [ ] heigh 높이는 그대로, width는 adjusted 적용
