### ISSUE TITLE
[Fix] 개최 프로세스 QA 반영

### ISSUE THREAD

**Issue by bangMinjI98** [TeamPINGLE/PINGLE-iOS#108]
## ❇️ 어떤 오류인가요?
<-- 오류에 대한 스크린샷이 있다면 첨부해주세요 -->
- 개최 프로세스에 대한 QA 진행 후 , 수정사항에 대해 반영할 예정입니다. 

## ❇️ 예상했던 결과는 무엇인가요?
<-- 예상했던 정상적인 결과에 대해 설명해주세요 -->
- QA에서 받았던 수정요청사항을 모두 반영하겠습니다. 

## ❇️ TODO
- [ ] [핑글 소개] 핑글 제목 글자수 제한 26자까지로 설정
- [ ] 장소 검색 두줄 처리
- [ ] 라이팅 ‘!’ 누락
- [ ] [카테고리 선택] 화면 크기에 따라 버튼 크기 조정 필요
- [ ] [텍스트 필드] 플레이스 홀더 텍스트 크기 확인 요청
- [ ] datepicker 뷰만 딤뷰 사라짐 -> 딤뷰 탭하면 딤뷰 사라지고,  원래 상태로 돌아오는 형태로 구현
- [ ] 장소 검색 선택 selectedRow nil 값으로 바꾸기
- [ ] [인원수 선택] 하단 ‘다음으로’ 버튼과 ‘나가기’ 영역 위치 확인 요청
- [ ] [장소 선택] 엠티뷰 ‘다른 장소로 검색해보세요’ 텍스트 누락
- [ ] [개최 안내] 에서 PIN 과 MINGLE 자간이 다름 
- [ ] [개최 안내] 그래픽 에셋 크기 조정 요청
- [ ] [인원 수 선택] 0이 무한으로 입력됨
- [ ] [인원 수 선택] 커서 색상 그린으로 변경 요청
