### ISSUE TITLE
[Fix] 1차 전체 QA 수정 사항 해결

### ISSUE THREAD

**Issue by chaentopia** [TeamPINGLE/PINGLE-iOS#109]
## ❇️ 어떤 오류인가요?

https://pinglepingle.notion.site/QA-ec8622b842264ac48733e9ca6f944958?pvs=4

## ❇️ 예상했던 결과는 무엇인가요?

https://pinglepingle.notion.site/QA-ec8622b842264ac48733e9ca6f944958?pvs=4

## ❇️ TODO
- [x]  [상단 카테고리 칩] 중앙 정렬 확인
- [x] [지도 카드] 카드뷰 참여현황 참여자 글씨 크기 확인 부탁 
- [x] 하단바 다른 버튼 누르고 개최버튼 누를시 하단바 active오류
- [x] [참여 현황] 숫자 부분 클릭 안됨
- [x] [내용 요약 및 확인] 개최 버튼 클릭 후 홈으로 이동
- [x]  회전 시 선택 후 카메라 이동 막힘
- [x] 홈 화면 카드 느리게 뜨는 이슈
- [x] 모집완료 레이아웃 이상함
- [x] 홈 화면 카드 장소 두줄 처리
- [x] 전체 텍스트필드 영어로 되어있음

## ❇️ 참고자료
x
