### ISSUE TITLE
[Feat] 기존 단체 입장하기 화면 구현

### ISSUE THREAD

**Issue by alstn38** [TeamPINGLE/PINGLE-iOS#12]
## ❇️ 어떤 기능인가요?
기존 단체 입장하는 화면에서 속해있는 단체 검색을 통해 등록된 단체를 찾는 화면입니다.

## ❇️ 뷰 및 기능 설계도
<img width="697" alt="스크린샷 2024-01-03 오후 9 00 58" src="https://github.com/TeamPINGLE/PINGLE-iOS/assets/62370742/64b32cd2-f586-4fc0-accc-54b746b0846c">

<img width="509" alt="스크린샷 2024-01-03 오후 5 28 14" src="https://github.com/TeamPINGLE/PINGLE-iOS/assets/62370742/27520256-6513-4ec6-8a70-c307e218a5fc">

## ❇️ TODO
- [x] 검색창 구현
- [x] CollectionView 구현
- [x] 빈 화면 클릭 시 키보드 숨김 구현
- [x] CollectionViewCell 단일 선택 구현
- [x] 단체 선택 시 다음으로 버튼 활성화 구현
- [x] 단체 직접 추가 선택 시 SafariServices 연결

## ❇️ 참고자료
https://fomaios.tistory.com/entry/%EC%84%9C%EC%B9%98%EB%B0%94-%EC%BB%A4%EC%8A%A4%ED%85%80%ED%95%98%EA%B8%B0-Custom-UISearchBar
