### ISSUE TITLE
[Network] 마이핑글 리스트 API 연결

### ISSUE THREAD

**Issue by chaentopia** [TeamPINGLE/PINGLE-iOS#133]
## ❇️ 연결하려는 API는 무엇인가요?
- 마이핑글 리스트 불러오는 API 연결

## ❇️ TODO
- [ ] 채팅 링크 DTO 수정
- [ ] API 연결
- [ ] Data 받아서 화면에 연결
- [ ] 참여완료 구현
- [ ] 취소하기 API 연결
