### ISSUE TITLE
[Refactor] 멘토님 피드백 반영

### ISSUE THREAD

**Issue by chaentopia** [TeamPINGLE/PINGLE-iOS#144]
## ❇️ 리팩토링 뷰 및 기능 설명

홈 화면 전반적인 멘토님 피드백 반영

## ❇️ 리팩토링 후 예상되는 결과는 무엇인가요?
앱 가동에 있어서는 동일한 결과이겠지만, 코드의 복잡성이 확 줄어들 것 같습니다..~

## ❇️ TODO
- [x] forEach append 문 -> map 고차함수로 수정
- [ ] 메소드 로직 분리
- [x] index 접근 코드 수정
- [x] private / private (set) 처리
- [ ] CLLocationManagerDelegate 호출 관리

## ❇️ 참고자료
https://angry-cousin-5d8.notion.site/608c9dc581ad475996ad19213d1b1f6b
