### ISSUE TITLE
[Refactor] 멘토님 피드백 반영

### ISSUE THREAD

**Issue by alstn38** [TeamPINGLE/PINGLE-iOS#145]
## ❇️ 리팩토링 뷰 및 기능 설명
<-- 관련 스크린샷이 있다면 첨부해주세요 -->
앱잼 데모데이에 받은 피드백을 수정할 예정입니다.

## ❇️ 리팩토링 후 예상되는 결과는 무엇인가요?
앱 사용시 설정에서 핑글에 관련한 애플 계정을 탈퇴할 경우 핑글 앱에서도 재로그인을 유도하겠습니다.

## ❇️ TODO
- [x] svg 이미지 처리
- [x] 이미지 에셋 키를 통한 추가
- [x] SceneDelegate 처리
- [x] 유저info 네트워크 오류 시에 대한 처리
- [x] 코드 전개 방식 줄바꿈

## ❇️ 참고자료
https://angry-cousin-5d8.notion.site/608c9dc581ad475996ad19213d1b1f6b
