### ISSUE TITLE
[Refactor] 멘토님 피드백 반영

### ISSUE THREAD

**Issue by bangMinjI98** [TeamPINGLE/PINGLE-iOS#147]
## ❇️ 리팩토링 뷰 및 기능 설명
<-- 관련 스크린샷이 있다면 첨부해주세요 -->
- 멘토님께 받은 피드백 사항 반영 

## ❇️ 리팩토링 후 예상되는 결과는 무엇인가요?
- 다른 방법으로 고쳐둔 오류들을 조언해주신대로 수정할 예정입니다 . 
- 주신 피드백을 토대로 한 화면에서 여러개의 View를 활용할 예정입니다. 

## ❇️ TODO
- [ ] navigationBar 오류 수정 
- [ ] progressBar 구현
- [ ] 여러개의 VC -> 하나의 VC에서 여러개의 View
- [ ]  svg 이미지 처리
- [ ]  에셋 키 관리 방법 변경
