### ISSUE TITLE
[Feat] 홈 화면 리스트뷰 구현

### ISSUE THREAD

**Issue by chaentopia** [TeamPINGLE/PINGLE-iOS#154]
## ❇️ 어떤 기능인가요?
3차 스프린트에 해당하는 리스트뷰를 구현할 예정입니다.
동시에 3차 스프린트의 기능인 검색 기능을 추가하기 위해서 리팩토링도 진행할 예정입니다.

## ❇️ 뷰 및 기능 설계도
![리스트뷰 UI](https://github.com/TeamPINGLE/PINGLE-iOS/assets/109775321/36d7284a-d23f-4eda-8e9b-f73fe2cae819)
![리스트뷰 UI empty](https://github.com/TeamPINGLE/PINGLE-iOS/assets/109775321/df9c7653-415a-4ee4-913b-6c70a211b002)
![홈 화면 기능 설계 - 3차](https://github.com/TeamPINGLE/PINGLE-iOS/assets/109775321/6afee458-aeca-464c-8534-44ccc47a864e)

## ❇️ TODO
- [x] 홈 화면 하나의 뷰컨으로 합치기
- [x] 홈 화면 상단 고정 UI 수정
- [ ] 리스트 뷰 UI 구현
