### ISSUE TITLE
[Feat] 신규 단체 개설 단체명 입력 UI 구현

### ISSUE THREAD

**Issue by alstn38** [TeamPINGLE/PINGLE-iOS#160]
## ❇️ 어떤 기능인가요?
신규 단체 개설을 위한 뷰입니다. 단체명, 대표 이메일을 입력 받습니다.

## ❇️ 뷰 및 기능 설계도
<img width="500" alt="스크린샷 2024-02-20 오후 9 53 14" src="https://github.com/TeamPINGLE/PINGLE-iOS/assets/62370742/7e9475b5-7123-49cd-bcb9-0d2f251708b3">
<img width="1040" alt="스크린샷 2024-02-20 오후 9 53 26" src="https://github.com/TeamPINGLE/PINGLE-iOS/assets/62370742/c3871fbb-b2ca-4114-927d-301e9ebc2766">

## ❇️ TODO
- [x] 단체명 입력창 구현
- [x] 중복확인 활성화
- [x] 앞, 뒤 공백 문자 제거
- [x] 토스트 메시지 노출
- [x] 대표 이메일 유효성 검사 수행
