### ISSUE TITLE
[Network] 랭킹뷰 API 연결 

### ISSUE THREAD

**Issue by bangMinjI98** [TeamPINGLE/PINGLE-iOS#161]
## ❇️ 연결하려는 API는 무엇인가요?
- 랭킹 API

## ❇️ TODO
- [ ] 랭킹 API 연결 
- [ ] 랭킹 없을 시 UI 분기처리 
- [ ] 스크롤 영역 조정
