### ISSUE TITLE
[Network] 단체 이름 중복 검사 API 연결

### ISSUE THREAD

**Issue by alstn38** [TeamPINGLE/PINGLE-iOS#163]
## ❇️ 연결하려는 API는 무엇인가요?
- 단체 이름 중복 검사 API

## ❇️ TODO
- [x] 중복검사를 통한 결과 토스트뷰 노출
- [x] 단체명, 이메일이 사용가능한 경우 다음으로 버튼 활성화
- [x] 단체 이름 중복 검사 API 연결
