### ISSUE TITLE
[Feat] 키워드 선택 화면 UI 작업

### ISSUE THREAD

**Issue by alstn38** [TeamPINGLE/PINGLE-iOS#166]
## ❇️ 어떤 기능인가요?
단체를 설명하는 키워드를 선택하는 화면입니다.

## ❇️ 뷰 및 기능 설계도
<img width="480" alt="스크린샷 2024-02-25 오후 8 14 58" src="https://github.com/TeamPINGLE/PINGLE-iOS/assets/62370742/32a2331a-923b-417a-9026-196a273e8a1d">
<img width="784" alt="스크린샷 2024-02-25 오후 8 15 16" src="https://github.com/TeamPINGLE/PINGLE-iOS/assets/62370742/d9616800-ea06-4f69-9fdb-2805bb7980df">

## ❇️ TODO
- [ ] 키워드 선택 UI 작업
- [ ] 키워드 단일 선택 기능
- [ ] 키워드 선택 시 다음으로 버튼 활성화
