### ISSUE TITLE
[Feat] Step 1: 카테고리 선택 뷰 UI 구현

### ISSUE THREAD

**Issue by bangMinjI98** [TeamPINGLE/PINGLE-iOS#17]
## ❇️ 어떤 기능인가요?
- 핑글 개최하기 프로세스 중  카테고리 선택 뷰

## ❇️ 뷰 및 기능 설계도
 ![이름 없는 노트북-02](https://github.com/TeamPINGLE/PINGLE-iOS/assets/113960786/9180cbef-5874-4e37-b3f6-fa3c7f80e764)  ![image](https://github.com/TeamPINGLE/PINGLE-iOS/assets/113960786/4fbd4966-4967-4b5e-91b5-d1b862838224) 

## ❇️ TODO
- [ ] 나가기 버튼 구현
- [ ] UILabel (StringLiterals 등록 후 사용) 
- [ ] PINGLECategory 버튼 커스텀 
- [ ] PINGLECTAButton 버튼 커스텀 
- [ ] 기기 대응 확인하기
