### ISSUE TITLE
[Feat] 단체 정보 확인 뷰 UI 작업

### ISSUE THREAD

**Issue by alstn38** [TeamPINGLE/PINGLE-iOS#170]
## ❇️ 어떤 기능인가요?
입력한 단체명, 대표 이메일, 선택한 키워드를 확인하여 단체 정보가 맞는지 확인하여 개설하는 페이지입니다.

## ❇️ 뷰 및 기능 설계도

<img width="395" alt="스크린샷 2024-02-26 오후 9 28 59" src="https://github.com/TeamPINGLE/PINGLE-iOS/assets/62370742/ceaddae2-d993-48a2-9cba-8b1b56032c83">

## ❇️ TODO
- [x] 입력한 단체명 표시하기
- [x] 대표 이메일 표시하기
- [x] 선택한 키워드 보여주기
- [x] 모임이름, 대표 이름에 따른 View 크기 조절
