### ISSUE TITLE
[Feat] 단체 개설 뷰 UI 작업 및 초대 초드 공유 기능

### ISSUE THREAD

**Issue by alstn38** [TeamPINGLE/PINGLE-iOS#180]
## ❇️ 어떤 기능인가요?
단체 개설 완료 이후 생성되는 뷰 UI 작업과 초대 코드 공유 기능을 추가하겠습니다.

## ❇️ 뷰 및 기능 설계도
<img width="1011" alt="스크린샷 2024-02-29 오후 7 22 23" src="https://github.com/TeamPINGLE/PINGLE-iOS/assets/62370742/4d42b777-0e86-4b91-be31-5edf6ad44985">
<img width="480" alt="스크린샷 2024-02-29 오후 7 22 59" src="https://github.com/TeamPINGLE/PINGLE-iOS/assets/62370742/c7675a2a-39a9-42e6-ad46-1552eb239a24">

## ❇️ TODO
- [ ] 단체 개설 완료, 초대코드 공유 UI 작업
- [ ] 초대코드 복사 기능
- [ ] 초대코드 공유 기능

## ❇️ 참고자료
https://tom7930.tistory.com/53
