### ISSUE TITLE
[Feat] 나의 단체 설정 UI 구현

### ISSUE THREAD

**Issue by alstn38** [TeamPINGLE/PINGLE-iOS#185]
## ❇️ 어떤 기능인가요?
가입한 단체의 목록을 볼 수 있는 화면입니다.

## ❇️ 뷰 및 기능 설계도
<img width="509" alt="스크린샷 2024-03-02 오후 3 30 58" src="https://github.com/TeamPINGLE/PINGLE-iOS/assets/62370742/c81f415f-f36b-46e4-a6b2-ef601df3bbf8">

## ❇️ TODO
- [x] 현재 설정된 단체 뷰 구현
- [x] 가입된 단체 CollectionView 구현
- [x] 새로운 단체 추가하러 가기 클릭 시 단체 가입 화면으로 이동
- [x] 해당 팝업창 뷰 구현
- [x] 새로운 단체 가입으로 연결
- [x] 토스트 뷰 구현
- [x] 클립보드 복사 구현
- [x] 공유하기 기능 구현
