### ISSUE TITLE
[Network] 나의 단체 가입된 그룹 API 연결

### ISSUE THREAD

**Issue by alstn38** [TeamPINGLE/PINGLE-iOS#188]
## ❇️ 연결하려는 API는 무엇인가요?
유저 가입 그룹 리스트 API

## ❇️ TODO
- [x] 유저 가입 그룹 리스트 API 호출
- [x] 저장된 그룹 id와 비교하여 현재 설정된 그룹 단체 정보 표시
- [x] 호출한 그룹 정보를 이용하여 단체 변경 구현
