### ISSUE TITLE
[Fix] 3차 스프린트 수정사항 반영

### ISSUE THREAD

**Issue by alstn38** [TeamPINGLE/PINGLE-iOS#189]
## ❇️ 어떤 오류인가요?

3차 스프린트로 넘어오면서 변경된 사항을 수정할 생각입니다.

## ❇️ 예상했던 결과는 무엇인가요?

Layout과 단체명, 기능들이 수정되어 잘 나타날 것 같습니다.

## ❇️ TODO
- [x] 개설하기에서 마지막 페이지 시 건너뛰기 버튼 Hidden 처리
- [x] 기존 단체 가입 시 검색 결과 cell 단체명 두줄 고려 UI 수정
- [x] 단체 검색시 키워드 라벨 위치 수정
- [x] 검색뷰 클리어 버튼 추가
- [x] 기존 단체 가입 시 "이미 가입된 단체입니다" 경고 토스트 뷰 구현
- [x] 기존단체 가입플로우에서 새로운 단체 만들기 버튼 이동 로직 변경
- [x] 새로운 단체명 글자 수 제한
- [x] 인터셉터 중복 수정
