### ISSUE TITLE
[Fix] 3차 스프린트 iOS QA 수정사항

### ISSUE THREAD

**Issue by alstn38** [TeamPINGLE/PINGLE-iOS#211]
## ❇️ 어떤 오류인가요?

<img width="372" alt="스크린샷 2024-03-07 오후 9 29 05" src="https://github.com/TeamPINGLE/PINGLE-iOS/assets/62370742/8e245996-2672-4952-9d52-b4e124d8ddf7">
<img width="234" alt="스크린샷 2024-03-07 오후 9 29 33" src="https://github.com/TeamPINGLE/PINGLE-iOS/assets/62370742/29ec73c4-50ec-4d20-8c26-70ebfe14e4dc">

## ❇️ TODO
- [x] 단체개설완료페이지 단체명 길이 제한
- [x] 신규단체 개설하고 홈화면이동시 모달창 나타나는 문제
- [x] 단체개설시 단체명 20자에서 받침안되는 문제
- [x] 단체변경시 초대코드 수정되지 않는 문제
