### ISSUE TITLE
[Fix] 3차 스프린트 자체 QA 수정 사항 반영

### ISSUE THREAD

**Issue by chaentopia** [TeamPINGLE/PINGLE-iOS#212]
## ❇️ 어떤 오류인가요?

자체 QA 진행 후 리스트업 예정

## ❇️ 예상했던 결과는 무엇인가요?

자체 QA 진행 후 리스트업 예정

## ❇️ TODO
- [x] 404 삭제 에러 ErrorMessage 추가 및 분기처리
- [x] 검색을 통해 들어간 지도뷰에서의 삭제 
- [x] 지도에서 다른 칩 선택 시 없을 때 리스트로 아예 바뀌어버림
- [x] 단체 변경 되었을때 단체명 바로 적용 안되고 앱 끄고 다시 들어가야 적용되는 이슈
