### ISSUE TITLE
[Fix] 3차 전체 스프린트 QA 반영 

### ISSUE THREAD

**Issue by bangMinjI98** [TeamPINGLE/PINGLE-iOS#219]
## ❇️ 어떤 오류인가요?
<-- 오류에 대한 스크린샷이 있다면 첨부해주세요 -->

- 3차 전체 스프린트 QA 반영 
-> 검색 페이지에서 검색바를 누르면 검색어가 지워지면서 검색 페이지로 이동 
-> 랭킹 엠티뷰 라이팅 중앙정렬
-> 검색 페이지 최초 진입시 키보드 위치 고정 
-> 개최 횟수 한 자리 수 일 때, 양 옆 마진값 맞추기 
-> 랭킹 숫자 크기 조정 

## ❇️ 예상했던 결과는 무엇인가요?
<-- 예상했던 정상적인 결과에 대해 설명해주세요 -->

## ❇️ TODO
- [ ] 검색 페이지에서 검색바를 누르면 검색어가 지워지면서 검색 페이지로 이동 
- [ ] 랭킹 엠티뷰 라이팅 중앙정렬
- [ ]  검색 페이지 최초 진입시 키보드 위치 고정 
- [ ] 개최 횟수 한 자리 수 일 때, 양 옆 마진값 맞추기 
- [ ]  랭킹 숫자 크기 조정
