### ISSUE TITLE
[Feat] 홈 화면 디테일 UI 구현

### ISSUE THREAD

**Issue by chaentopia** [TeamPINGLE/PINGLE-iOS#23]
## ❇️ 어떤 기능인가요?
홈 화면에서 보여지는 핀을 터치했을 때 나와지는 뷰를 구현할 예정입니다. (로직까지 포함)

## ❇️ 뷰 및 기능 설계도
![지도 화면 상세 정보 UI 설계](https://github.com/TeamPINGLE/PINGLE-iOS/assets/109775321/28ae82e6-5740-4230-a054-71db68bbc686)
![지도 화면 상세 정보 - 팝업 UI 설계](https://github.com/TeamPINGLE/PINGLE-iOS/assets/109775321/cc5235cb-00da-4de7-ae3a-6fba3b5af442)
![홈 화면 기능 설계](https://github.com/TeamPINGLE/PINGLE-iOS/assets/109775321/1ca5d974-992f-4925-a2f7-1c505c553c7b)

## ❇️ TODO
- [x] 핀 액션 연결
- [x] 띄워지는 뷰 커스텀
- [x] 뷰 연결 - 버튼 없애기 
- [x] 뷰 연결 - 핀 크기 커지고 카메라 이동 (미정)
- [x] 팝업 UI 구현
- [x] 팝업 로직 연결

## ❇️ 참고자료
https://thecosmos.tistory.com/6

https://leemyungjic.tistory.com/52

-> touchHandler
