### ISSUE TITLE
[Feat] Step 2: 제목, 한줄 소개 View UI구현

### ISSUE THREAD

**Issue by bangMinjI98** [TeamPINGLE/PINGLE-iOS#28]
## ❇️ 어떤 기능인가요?
- 핑글 개최 프로세스 중 Step 2: 제목, 한줄 소개 에 해당하는 뷰 UI 

## ❇️ 뷰 및 기능 설계도
![이름 없는 노트북-03](https://github.com/TeamPINGLE/PINGLE-iOS/assets/113960786/d5d9449a-9e7b-4ae2-ace8-3ae4bbd9a67e)
![image](https://github.com/TeamPINGLE/PINGLE-iOS/assets/113960786/8e68303b-a41e-46f8-b48e-bacf7b8a7230)

## ❇️ TODO
- [ ] backButton으로 전단계 화면 pop
- [ ] UILabel, UIImageView로 상단 프로그래스바, stepTitle 구현 
- [ ] Textfield Class 활용
- [ ] 다음으로, 나가기 버튼 custom class 활용
