### ISSUE TITLE
[Feat] 기존 단체 입장 초대 코드 입력 뷰 UI 구현

### ISSUE THREAD

**Issue by alstn38** [TeamPINGLE/PINGLE-iOS#29]
## ❇️ 어떤 기능인가요?
기존 단체 입장 할 때 초대코드를 입력하는 화면입니다.

## ❇️ 뷰 및 기능 설계도

![스크린샷 2024-01-05 오후 3 02 42](https://github.com/TeamPINGLE/PINGLE-iOS/assets/62370742/54bf30d7-ae30-415a-8937-8c22109a4216)

![스크린샷 2024-01-05 오후 3 02 12](https://github.com/TeamPINGLE/PINGLE-iOS/assets/62370742/143273e6-ccca-411e-b494-afb562be0d4b)

## ❇️ TODO
- [x] 단체 정보 뷰 만들기
- [x] 단체 초대 코드 입력 textField 기능 구현
- [x] 초대 코드 오류 토스트 뷰 구현
- [x] 입장하기 버튼 구현
