### ISSUE TITLE
[Chore] 중간과제 리드미 작성 

### ISSUE THREAD

**Issue by chaentopia** [TeamPINGLE/PINGLE-iOS#33]
## ❇️ 이슈에 대해 설명해주세요
중간과제로 제출할 리드미를 만들겠습니다..

## ❇️ TODO
- [ ] 1. 간단한 프로젝트 설명 
- [ ] 2. 참여 구성원 및 구성원 사진 ^^ (남는건 사진뿐이랍니다 여러분)
- [ ] 3. Coding Convention
- [ ] 4. Git branch 전략
- [ ] 5. 프로젝트 폴더링 Convention

## ❇️ 참고자료
x
