### ISSUE TITLE
[Feat] 설정 화면 UI 구현

### ISSUE THREAD

**Issue by alstn38** [TeamPINGLE/PINGLE-iOS#36]
## ❇️ 어떤 기능인가요?
핑글 어플의 설정화면입니다.
이름, 소속된 단체, 문의사항, 공지사항, 버전, 로그아웃, 탈퇴 기능이 있습니다.

## ❇️ 뷰 및 기능 설계도

<img width="650" alt="스크린샷 2024-01-06 오후 4 56 35" src="https://github.com/TeamPINGLE/PINGLE-iOS/assets/62370742/66d6df20-dc1f-4c54-9540-69c9a89403d4">
<img width="482" alt="스크린샷 2024-01-06 오후 4 56 57" src="https://github.com/TeamPINGLE/PINGLE-iOS/assets/62370742/cdb90646-8459-4da8-93a8-00e6ba08b271">

## ❇️ TODO
- [x] 설정 화면 UI 구현
- [x] 나의 단체 버튼 구현
- [x] 로그아웃, 계정탈퇴 커스텀 뷰 구현
