### ISSUE TITLE
[Feat] 나가기 모달 view 구현 

### ISSUE THREAD

**Issue by bangMinjI98** [TeamPINGLE/PINGLE-iOS#48]
## ❇️ 어떤 기능인가요?
- 핑글 개최 작성 중 나가기 버튼을 눌렀을때 뜨는 확인 모달입니다. 

## ❇️ 뷰 및 기능 설계도
![all_modal](https://github.com/TeamPINGLE/PINGLE-iOS/assets/113960786/2ee354b2-0a87-4b82-a91d-736e5e36ccf9)

## ❇️ TODO
- [ ] 나가기 확인 모달 UIView class 구현 
- [ ] 나가기 버튼 구현
- [ ] 이어서 작성 버튼 구현 
- [ ] ViewController 나가기 버튼에 동작 연결
