### ISSUE TITLE
[Fix] 온보딩 화면 디자인 수정에 따른 UI 작업

### ISSUE THREAD

**Issue by alstn38** [TeamPINGLE/PINGLE-iOS#51]
## ❇️ 어떤 수정인가요?
<-- 오류에 대한 스크린샷이 있다면 첨부해주세요 -->
온보딩 디자인 변경에 따른 수정입니다.

## ❇️ 예상했던 결과는 무엇인가요?
글자와 프래임만 변경될 예정입니다.

## ❇️ TODO
- [ ] 회원가입 뷰 글자 변경
- [ ] 온보딩 뷰 글자, 프래임 변경
- [ ] 기존단체 입장 글자 변경
- [ ] 초대코드 입력 글자 변경
- [ ] 단체입장 완료 글자 변경
