### ISSUE TITLE
[Network] 로그인 API 연결, 유저 정보 API 연결, 시작화면 분기처리

### ISSUE THREAD

**Issue by alstn38** [TeamPINGLE/PINGLE-iOS#63]
## ❇️ 연결하려는 API는 무엇인가요?
로그인 API 연결, 유저 정보 API 연결, 시작화면 분기처리

## ❇️ TODO
- [x] 로그인 API 연결
- [x] 로그인에 따른 SceneDelegate연결.
- [x] 유저정보 API 연결

## ❇️ 참고자료
https://developer.apple.com/documentation/authenticationservices/implementing_user_authentication_with_sign_in_with_apple
