### ISSUE TITLE
[Fix] 로그인, 온보딩 플로우 디자인 수정과 구글폼 링크 연결

### ISSUE THREAD

**Issue by alstn38** [TeamPINGLE/PINGLE-iOS#74]
## ❇️ 어떤 수정인가요?
- 3D 디자인 에셋 추가에 따른 이미지 에셋 추가하겠습니다.
- 구글폼 링크가 생성되어 구글폼 링크 수정하겠습니다.

## ❇️ TODO
- [x] 회원가입 로고 수정
- [x] 온보딩 버튼 이미지 에셋 추가
- [x] 구글폼 링크 수정
- [x] 단체 입장 완료 이미지 에셋 추가
