### ISSUE TITLE
[Network] 기존 단체 입장 초대코드 화면 네트워크 구현

### ISSUE THREAD

**Issue by alstn38** [TeamPINGLE/PINGLE-iOS#78]
## ❇️ 연결하려는 API는 무엇인가요?
- 단체 디테일 조회 API
- 단체 가입 API

## ❇️ TODO
- [x] 단체 디테일 조회 API 연결
- [x] 단체 가입 API 연결
- [x] 단체 가입 완료 시 그룹 id와 이름을 로컬 디비에 저장하기.
