### ISSUE TITLE
[Feat] 핑글 개최뷰 싱글톤 클래스 생성 및 결과 요약 페이지 확인 

### ISSUE THREAD

**Issue by bangMinjI98** [TeamPINGLE/PINGLE-iOS#79]
## ❇️ 어떤 기능인가요?
- 싱글톤 클래스를 이용하여 각 viewController에서 받아온 데이터를 결과 요약 페이지에서 보여줍니다. 

## ❇️ 뷰 및 기능 설계도
![1차_iOS_개최_Step7](https://github.com/TeamPINGLE/PINGLE-iOS/assets/113960786/c469970f-8a64-4441-b05a-d50e28cdebdb)

## ❇️ TODO
- [ ] 싱글톤 클래스 생성 
- [ ] 각 viewController에 데이터를 저장할 변수 설정 
- [ ] 결과 요약 페이지에 load 되는지 확인
