### ISSUE TITLE
[Network] 설정화면 네트워크 구현

### ISSUE THREAD

**Issue by alstn38** [TeamPINGLE/PINGLE-iOS#82]
## ❇️ 연결하려는 API는 무엇인가요?
- 로그아웃 API
- 회원탈퇴 API

## ❇️ TODO
- [x] 로그아웃 API 구현
- [x] 회원탈퇴 API 구현
- [x] 로그아웃 시 이름 제외한 저장된 어세스 토큰, 리프레쉬 토큰, 가입 단체 제거
- [x] 회원탈퇴 시 로그아웃 관련 삭제와 더불어 애플 관련 모든 것 삭제.
