### ISSUE TITLE
[Fix] 홈 화면 이슈 대응

### ISSUE THREAD

**Issue by chaentopia** [TeamPINGLE/PINGLE-iOS#90]
## ❇️ 어떤 오류인가요?

재사용이 안되는 이슈와.. 홈 화면 진입할 때마다 새로 업데이트 할 수 있도록 할 예정입니다.
서버통신 에러 처리 또한 할 예정입니다.
또한 필터링 시 한 장소에 대한 다양한 카테고리의 모임이 열렸을 때 경우의 서버 안드로이드와의 논의사항에서 결정된 사항들을 추가할 예정입니다.

## ❇️ 예상했던 결과는 무엇인가요?

핀을 탭했을 때마다 실시간으로 정보를 반영해야 하는데 이부분이 재사용 이슈 때문에 되지 않는 것 같습니다.

## ❇️ TODO
- [x] 재사용 이슈
- [x] 홈 화면 viewWillAppear 통신
- [x] 홈 화면 필터링 통신
- [ ] 대화하기 버튼 없을 때 에러 처리
- [x] 자체 필터링이 아닌 서버 필터링으로 처리

## ❇️ 참고자료
x
